In [127]:
import polars as pl
from scipy.stats import fisher_exact
from pathlib import Path
import os
from tqdm.auto import tqdm

os.chdir('/home/vladimirnoz/Projects/Codebook_Perspectives/AS_CHS_GHTS')

TABLES_PATH = Path('joint_tables/')
SIGNIF_THR = 0.01

In [128]:
tables_list = []

for path in tqdm(sorted(TABLES_PATH.glob('ASB_Phenotypes/*.tsv'))):
    local_df = pl.read_csv(
        path, 
        separator='\t',
        schema_overrides = {
            'bads': pl.String,
            'ref_counts': pl.String,
            'alt_counts': pl.String,
            'ref_es': pl.String,
            'alt_es': pl.String,
            'ref_pval': pl.String,
            'alt_pval': pl.String,
        }
    )
    tf = path.stem
    exp = path.parent.parent.stem
    local_df = local_df.with_columns(
        tf = pl.lit(tf), 
        exp = pl.lit(exp),
    )
    tables_list.append(local_df)
df = pl.concat(tables_list, how="vertical_relaxed")
df

  0%|          | 0/1 [00:00<?, ?it/s]

shape: (143_013, 26)
┌───────┬───────────┬───────────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ #chr  ┆ start     ┆ end       ┆ mean_bad ┆ … ┆ ADASTRA_TF ┆ ADASTRA_CL ┆ tf         ┆ exp        │
│ ---   ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str   ┆ i64       ┆ i64       ┆ f64      ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞═══════╪═══════════╪═══════════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 17275695  ┆ 17275696  ┆ 2.0      ┆ … ┆ ZN350_HUMA ┆ primary_hu ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆ N;BRD4_HUM ┆ man_epider ┆ seq        ┆ es         │
│       ┆           ┆           ┆          ┆   ┆ AN;PBX4_HU ┆ mal_kerati ┆            ┆            │
│       ┆           ┆           ┆          ┆   ┆ …          ┆ …          ┆            ┆            │
│ chr1  ┆ 17275729  ┆ 17275730  ┆ 2.0      ┆ … ┆ ZN350_HUMA ┆ HEK293__em ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆ N;ZN776_HU ┆ bryonic_ki ┆ seq        ┆ es         │
│       ┆           ┆           ┆          ┆   ┆ MAN        ┆ dney_      ┆            ┆            │
│ chr1  ┆ 44731028  ┆ 44731029  ┆ 2.0      ┆ … ┆ MIER1_HUMA ┆ thyroid_gl ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆ N;TF65_HUM ┆ and;LoVo__ ┆ seq        ┆ es         │
│       ┆           ┆           ┆          ┆   ┆ AN;ZN610_H ┆ colorectal ┆            ┆            │
│       ┆           ┆           ┆          ┆   ┆ …          ┆ …          ┆            ┆            │
│ chr1  ┆ 44731045  ┆ 44731046  ┆ 2.0      ┆ … ┆ FOXK2_HUMA ┆ HAEC__huma ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆ N;BRD9_HUM ┆ n_aortic_e ┆ seq        ┆ es         │
│       ┆           ┆           ┆          ┆   ┆ AN;SMAD2_H ┆ ndothelial ┆            ┆            │
│       ┆           ┆           ┆          ┆   ┆ …          ┆ …          ┆            ┆            │
│ chr1  ┆ 55335837  ┆ 55335838  ┆ 2.0      ┆ … ┆ -          ┆ -          ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆            ┆            ┆ seq        ┆ es         │
│ …     ┆ …         ┆ …         ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ chr2  ┆ 234060729 ┆ 234060730 ┆ 3.0      ┆ … ┆ ZNF24_HUMA ┆ HepG2__hep ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆ N;SSRP1_HU ┆ atoblastom ┆ seq        ┆ es         │
│       ┆           ┆           ┆          ┆   ┆ MAN;ZN207_ ┆ a_;HT1080_ ┆            ┆            │
│       ┆           ┆           ┆          ┆   ┆ …          ┆ …          ┆            ┆            │
│ chr4  ┆ 49315259  ┆ 49315260  ┆ 3.0      ┆ … ┆ -          ┆ -          ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆            ┆            ┆ seq        ┆ es         │
│ chr6  ┆ 170163845 ┆ 170163846 ┆ 2.0      ┆ … ┆ -          ┆ -          ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆            ┆            ┆ seq        ┆ es         │
│ chr5  ┆ 176801718 ┆ 176801719 ┆ 3.0      ┆ … ┆ -          ┆ -          ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆            ┆            ┆ seq        ┆ es         │
│ chr10 ┆ 127261301 ┆ 127261302 ┆ 3.0      ┆ … ┆ -          ┆ -          ┆ selex+chip ┆ joint_tabl │
│       ┆           ┆           ┆          ┆   ┆            ┆            ┆ seq        ┆ es         │
└───────┴───────────┴───────────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [129]:
print(len(df))
print(len(df.filter(pl.col('fdr_comb_pval') < 0.05)))

143013
22064

In [134]:
calc = df.lazy().with_columns(
    signif = pl.col('fdr_comb_pval') < SIGNIF_THR
)

phenotypes = [
     'ebi',
     'eQTL_cis',
     'ADASTRA_TF',
]

calc = calc.with_columns(
    [(pl.col(x) != '-').alias(x) for x in phenotypes]
    
).group_by(
    [
        '#chr', 
        'start', 
        'end', 
        'id', 
        'ref', 
        'alt',
    ]
).agg(
   [pl.col(x).max().alias(x) for x in phenotypes + ['signif']]
)

In [135]:
aggs = [
    pl.col("signif").sum().alias("tot_sig"),
    (~pl.col("signif")).sum().alias("tot_not_sig")
]

for p in phenotypes:
    aggs.append((pl.col(p) & pl.col("signif")).sum().alias(f"{p}_n1"))
    aggs.append((pl.col(p) & ~pl.col("signif")).sum().alias(f"{p}_n2"))

counts = calc.select(aggs).collect()
print(counts)
total_sig = counts["tot_sig"][0]
total_not_sig = counts["tot_not_sig"][0]

results = []

for p in phenotypes:
    n1 = counts[f"{p}_n1"][0]
    n2 = counts[f"{p}_n2"][0]
    n3 = total_sig - n1
    n4 = total_not_sig - n2
    
    table = [[n1, n2], [n3, n4]]
    odds, pval = fisher_exact(table)
    
    results.append({
        "phenotype": p,
        "N1 (P+ S+)": n1,
        "N2 (P+ S-)": n2,
        "N3 (P- S+)": n3,
        "N4 (P- S-)": n4,
        "odds_ratio": odds,
        "p_value": pval,
        "signif_%": f'{n1/(n1+n3):.0%}'
    })

final_stats = pl.DataFrame(results)
final_stats

shape: (1, 8)
┌─────────┬─────────────┬────────┬────────┬─────────────┬─────────────┬──────────────┬─────────────┐
│ tot_sig ┆ tot_not_sig ┆ ebi_n1 ┆ ebi_n2 ┆ eQTL_cis_n1 ┆ eQTL_cis_n2 ┆ ADASTRA_TF_n ┆ ADASTRA_TF_ │
│ ---     ┆ ---         ┆ ---    ┆ ---    ┆ ---         ┆ ---         ┆ 1            ┆ n2          │
│ u32     ┆ u32         ┆ u32    ┆ u32    ┆ u32         ┆ u32         ┆ ---          ┆ ---         │
│         ┆             ┆        ┆        ┆             ┆             ┆ u32          ┆ u32         │
╞═════════╪═════════════╪════════╪════════╪═════════════╪═════════════╪══════════════╪═════════════╡
│ 11142   ┆ 111222      ┆ 1144   ┆ 8716   ┆ 7973        ┆ 72608       ┆ 10272        ┆ 92358       │
└─────────┴─────────────┴────────┴────────┴─────────────┴─────────────┴──────────────┴─────────────┘

shape: (3, 8)
┌─────────────┬────────┬────────────┬────────────┬────────────┬────────────┬────────────┬──────────┐
│ phenotype   ┆ N1 (P+ ┆ N2 (P+ S-) ┆ N3 (P- S+) ┆ N4 (P- S-) ┆ odds_ratio ┆ p_value    ┆ signif_% │
│ ---         ┆ S+)    ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ str         ┆ ---    ┆ i64        ┆ i64        ┆ i64        ┆ f64        ┆ f64        ┆ str      │
│             ┆ i64    ┆            ┆            ┆            ┆            ┆            ┆          │
╞═════════════╪════════╪════════════╪════════════╪════════════╪════════════╪════════════╪══════════╡
│ ebi         ┆ 1144   ┆ 8716       ┆ 9998       ┆ 102506     ┆ 1.34569    ┆ 3.7921e-18 ┆ 10%      │
│ eQTL_cis    ┆ 7973   ┆ 72608      ┆ 3169       ┆ 38614      ┆ 1.338011   ┆ 1.7686e-41 ┆ 72%      │
│ ADASTRA_TF  ┆ 10272  ┆ 92358      ┆ 870        ┆ 18864      ┆ 2.411543   ┆ 3.8992e-16 ┆ 92%      │
│             ┆        ┆            ┆            ┆            ┆            ┆ 2          ┆          │
└─────────────┴────────┴────────────┴────────────┴────────────┴────────────┴────────────┴──────────┘