In [71]:
import os
from glob import glob
from subprocess import run
from io import StringIO

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

os.chdir('/home/vladimirnoz/Projects/Codebook_Perspectives/')

In [72]:
# number of matrices

len(glob('motifs/manual_motifs_v2/pwms/*.pwm'))

235

In [73]:
# number of peaks
peaks = glob('peaks/chipseq+ghtselex/*.bed')
tfs_with_peaks = set([x.split('/')[-1].split('.')[0] for x in peaks])
len(tfs_with_peaks)

216

In [74]:
# number of TOPs

len(glob('TOPs/TOPs/*.bed'))

136

In [75]:
reads = glob('/home/vladimirnoz/AS_GHT_SELEX/chipseq-as/mapped_filtered_*/*.bam') + glob('/home/vladimirnoz/AS_GHT_SELEX/affiseq-as/mapped_filtered/*')
tfs_with_reads = set([x.split('/')[-1].split('.')[0] for x in reads])
len(tfs_with_reads)

207

In [76]:
'ZNF705EP' in tfs_with_reads

True

# ASB Stats

In [77]:
# snv unique positions

snps = glob('AS_CHS_GHTS/as_tables/*/*/*.tsv')
ids = set()
for file in snps:
    table = pd.read_table(file)
    ids = ids | set(table['id'])
len(ids)

122364

In [78]:
# snv unique positions with asb

snps = glob('AS_CHS_GHTS/as_tables/*/*/*.tsv')
ids = set()
for file in snps:
    table = pd.read_table(file).query('fdr_comb_pval < 0.05')
    ids = ids | set(table['id'])
len(ids)

10009

In [79]:
# chip-seq

#num_snps
snps = glob('AS_CHS_GHTS/SNPs_filtered/chipseq/*/*.vcf.gz')
total_snps = 0
for path in tqdm(snps):
    cmd = f'bcftools view -H {path} | wc -l'
    output = run(cmd, shell=True, text=True, capture_output=True).stdout
    num = int(output.strip())
    total_snps += num
print(total_snps)

  0%|          | 0/361 [00:00<?, ?it/s]

889814

In [80]:
# chip-seq

#num_tfs
tfs = glob('AS_CHS_GHTS/SNPs_filtered/chipseq/*')
len(tfs)

155

In [83]:
# chip-seq stats

datasets = glob('AS_CHS_GHTS/as_tables/chipseq/ASB_motifs/*.tsv')
total_asb = 0
pwm_hits = 0
concordant_hits = 0
strongly_concordant = 0
tfs = set()

for path in tqdm(datasets):
    df = pd.read_table(path).query('fdr_comb_pval < 0.05')
    if len(df) == 0:
        continue
    total_asb += len(df)
    tfs.add(path.split('/')[-1].split('.')[0])

    pwm_hits += len(df.query('motif_conc != "No Hit"'))
    concordant_hits += len(df.query('motif_conc == "Concordant"'))
    strongly_concordant += len(df.query('motif_conc == "Concordant" & abs(motif_fc) >= 1'))

    
print(len(tfs))
print(total_asb)
print(pwm_hits, f'{pwm_hits/total_asb:.0%}')
print(concordant_hits, f'{concordant_hits/pwm_hits:.0%}')
print(strongly_concordant)

  0%|          | 0/155 [00:00<?, ?it/s]

134
10575
2809 27%
1897 68%
1373

In [8]:
# ght-selex

#num_snps
snps = glob('AS_CHS_GHTS/SNPs_filtered/selex/*/*.vcf.gz')
total_snps = 0
for path in tqdm(snps):
    cmd = f'bcftools view -H {path} | wc -l'
    output = run(cmd, shell=True, text=True, capture_output=True).stdout
    num = int(output.strip())
    total_snps += num
print(total_snps)

  0%|          | 0/1303 [00:00<?, ?it/s]

35183

In [9]:
# ght-selex

#num_tfs
tfs = glob('AS_CHS_GHTS/SNPs_filtered/selex/*')
len(tfs)

178

In [10]:
# ght-selex

#num_experiments
datasets = glob('AS_CHS_GHTS/SNPs_filtered/selex/*/*')
len(set([x.split('.')[1] for x in datasets]))

370

In [84]:
# ght-selex stats

datasets = glob('AS_CHS_GHTS/as_tables/selex/ASB_motifs/*.tsv')
total_asb = 0
pwm_hits = 0
concordant_hits = 0
strongly_concordant = 0
tfs = set()

for path in tqdm(datasets):
    df = pd.read_table(path).query('fdr_comb_pval < 0.05')
    if len(df) == 0:
        continue
    total_asb += len(df)
    tfs.add(path.split('/')[-1].split('.')[0])

    pwm_hits += len(df.query('motif_conc != "No Hit"'))
    concordant_hits += len(df.query('motif_conc == "Concordant"'))
    strongly_concordant += len(df.query('motif_conc == "Concordant" & abs(motif_fc) >= 1'))

    
print(len(tfs))
print(total_asb)
print(pwm_hits, f'{pwm_hits/total_asb:.0%}')
print(concordant_hits, f'{concordant_hits/pwm_hits:.0%}')
print(strongly_concordant)

  0%|          | 0/178 [00:00<?, ?it/s]

162
1485
755 51%
469 62%
309

In [12]:
# Total ASBs

datasets = glob('AS_CHS_GHTS/as_tables/*/ASB_motifs/*.tsv')
total_asb = 0
pwm_hits = 0
concordant_hits = 0

for path in tqdm(datasets):
    df = pd.read_table(path).query('fdr_comb_pval < 0.05')
    if len(df) == 0:
        continue
    total_asb += len(df)

    pwm_hits += len(df.query('motif_conc != "No Hit"'))
    concordant_hits += len(df.query('motif_conc == "Concordant"'))

    

print(total_asb)
print(pwm_hits, f'{pwm_hits/total_asb:.0%}')
print(concordant_hits, f'{concordant_hits/pwm_hits:.0%}')

  0%|          | 0/333 [00:00<?, ?it/s]

12060
3564 30%
2366 66%

In [13]:
# ASBs in TOPs

datasets = glob('AS_CHS_GHTS/as_tables/*/ASB_motifs/*.tsv')
asbs_in_tops = 0


for path in tqdm(datasets):
    df = pd.read_table(path).query('fdr_comb_pval < 0.05')
    tf = os.path.basename(path).replace('.tsv', '')
    top_path = f'TOPs/TOPs/{tf}.bed'
    cmd = f'bedtools intersect -a stdin -b {top_path}'
    df_text = df.to_csv(index=False, sep='\t')
    proc = run(cmd, shell=True, text=True, capture_output=True, input=df_text)
    output = proc.stdout
    asbs_in_tops += len(output.split('\n'))
asbs_in_tops

  0%|          | 0/333 [00:00<?, ?it/s]

858

# Joint Collection & Remake

In [86]:
from pathlib import Path
import os

import polars as pl

import pandas as pd
from openpyxl import load_workbook, Workbook
from openpyxl.styles import Font
from copy import copy


os.chdir('/home/vladimirnoz/Projects/Codebook_Perspectives/AS_CHS_GHTS/')

TF_TABLES_PATH = Path('as_tables/')
JOINT_PATH = Path('joint_tables/ASB_Phenotypes/selex+chipseq.tsv')
TF_TYPES_PATH = Path('../common/tftypes.txt')
OUTPUT_DIR_PATH = Path('collection/')
FDR_THR = 0.05


fdr_filter = (pl.col('fdr_comb_pval') < 0.05)

In [87]:
types = pl.read_csv(TF_TYPES_PATH, separator='\t', has_header=False, new_columns=['tf', 'type'])
types

shape: (394, 2)
┌────────┬─────────────┐
│ tf     ┆ type        │
│ ---    ┆ ---         │
│ str    ┆ str         │
╞════════╪═════════════╡
│ KDM5B  ┆ Codebook TF │
│ ARID2  ┆ Codebook TF │
│ AHCTF1 ┆ Codebook TF │
│ AHDC1  ┆ Codebook TF │
│ AKNA   ┆ Codebook TF │
│ …      ┆ …           │
│ RORB   ┆ Control     │
│ RXRA   ┆ Control     │
│ VDR    ┆ Control     │
│ NFKB1  ┆ Control     │
│ GFP    ┆ Control     │
└────────┴─────────────┘

In [96]:
tables_list = []

for path in TF_TABLES_PATH.glob('*/ASB_motifs/*.tsv'):
    tf, exp = path.stem.replace('ZNF705EP', 'ZNF705E'), path.parent.parent.stem
    local_df = pl.read_csv(path, separator='\t', infer_schema_length=10000)
    local_df = local_df.filter(fdr_filter).with_columns(
        pl.lit(tf).alias('tf'),
        pl.lit(exp).alias('experiment_type'),
    )
    tables_list.append(local_df)

tf_table = pl.concat(tables_list, how='vertical_relaxed')

In [97]:
tf_table

shape: (12_060, 37)
┌───────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬────────┬─────────────────┐
│ #chr  ┆ start    ┆ end      ┆ mean_bad ┆ … ┆ motif_fc  ┆ motif_conc ┆ tf     ┆ experiment_type │
│ ---   ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---    ┆ ---             │
│ str   ┆ i64      ┆ i64      ┆ f64      ┆   ┆ f64       ┆ str        ┆ str    ┆ str             │
╞═══════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪════════╪═════════════════╡
│ chr19 ┆ 36128053 ┆ 36128054 ┆ 4.0      ┆ … ┆ 2.956331  ┆ No Hit     ┆ ZNF551 ┆ chipseq         │
│ chr17 ┆ 50909778 ┆ 50909779 ┆ 2.0      ┆ … ┆ -0.422304 ┆ No Hit     ┆ ZNF551 ┆ chipseq         │
│ chr15 ┆ 71307911 ┆ 71307912 ┆ 1.0      ┆ … ┆ 1.055859  ┆ No Hit     ┆ ZNF551 ┆ chipseq         │
│ chr10 ┆ 46422792 ┆ 46422793 ┆ 2.0      ┆ … ┆ -0.422372 ┆ No Hit     ┆ ZNF551 ┆ chipseq         │
│ chr19 ┆ 39533621 ┆ 39533622 ┆ 4.0      ┆ … ┆ -1.055821 ┆ No Hit     ┆ ZNF551 ┆ chipseq         │
│ …     ┆ …        ┆ …        ┆ …        ┆ … ┆ …         ┆ …          ┆ …      ┆ …               │
│ chr12 ┆ 77444268 ┆ 77444269 ┆ 2.0      ┆ … ┆ 0.98552   ┆ No Hit     ┆ PAX7   ┆ selex           │
│ chr13 ┆ 68370895 ┆ 68370896 ┆ 2.0      ┆ … ┆ -0.915332 ┆ No Hit     ┆ PAX7   ┆ selex           │
│ chr15 ┆ 73125484 ┆ 73125485 ┆ 2.0      ┆ … ┆ -0.070267 ┆ No Hit     ┆ PAX7   ┆ selex           │
│ chr15 ┆ 97024803 ┆ 97024804 ┆ 2.0      ┆ … ┆ 0.211301  ┆ No Hit     ┆ PAX7   ┆ selex           │
│ chr18 ┆ 69797083 ┆ 69797084 ┆ 2.0      ┆ … ┆ -2.675075 ┆ No Hit     ┆ PAX7   ┆ selex           │
└───────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴────────┴─────────────────┘

In [98]:
#unique tfs by types
tf_table_df = tf_table.lazy()
tf_table_df = tf_table_df.join(types.lazy(), on=['tf'])
tf_table_df.group_by(
    ['type']
).agg(
    pl.col('tf').n_unique()
).collect()

shape: (2, 2)
┌─────────────┬─────┐
│ type        ┆ tf  │
│ ---         ┆ --- │
│ str         ┆ u32 │
╞═════════════╪═════╡
│ Control     ┆ 39  │
│ Codebook TF ┆ 152 │
└─────────────┴─────┘

In [90]:
#unique signif SNPs

tf_table.group_by(
    ['#chr', 'end', 'id']
).len().select(pl.len())

shape: (1, 1)
┌───────┐
│ len   │
│ ---   │
│ u32   │
╞═══════╡
│ 10009 │
└───────┘

In [91]:
#unique signif SNPs

tf_table.group_by(
    ['#chr', 'end', 'id', 'experiment_type']
).len().group_by(
    'experiment_type'    
).len()

shape: (2, 2)
┌─────────────────┬──────┐
│ experiment_type ┆ len  │
│ ---             ┆ ---  │
│ str             ┆ u32  │
╞═════════════════╪══════╡
│ chipseq         ┆ 8750 │
│ selex           ┆ 1338 │
└─────────────────┴──────┘

In [92]:
table = pl.read_csv(JOINT_PATH, separator='\t', infer_schema_length=10000).filter(fdr_filter)
table = table.drop(pl.col('ADASTRA_CL'))
print(len(table))

22064

In [93]:
table

shape: (22_064, 23)
┌───────┬───────────┬───────────┬──────────┬───┬─────┬───────────────┬──────────────┬──────────────┐
│ #chr  ┆ start     ┆ end       ┆ mean_bad ┆ … ┆ ebi ┆ eQTL_cis      ┆ eQTL_cis_gen ┆ ADASTRA_TF   │
│ ---   ┆ ---       ┆ ---       ┆ ---      ┆   ┆ --- ┆ ---           ┆ e            ┆ ---          │
│ str   ┆ i64       ┆ i64       ┆ f64      ┆   ┆ str ┆ str           ┆ ---          ┆ str          │
│       ┆           ┆           ┆          ┆   ┆     ┆               ┆ str          ┆              │
╞═══════╪═══════════╪═══════════╪══════════╪═══╪═════╪═══════════════╪══════════════╪══════════════╡
│ chr2  ┆ 109614114 ┆ 109614115 ┆ 1.0      ┆ … ┆ -   ┆ Adipose_Subcu ┆ ENSG00000186 ┆ ZN217_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ taneous;Adipo ┆ 522.14;ENSG0 ┆ PRDM4_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ se_V…         ┆ 000019…      ┆ CTBP1_…      │
│ chr7  ┆ 157010642 ┆ 157010643 ┆ 2.0      ┆ … ┆ -   ┆ Esophagus_Muc ┆ ENSG00000130 ┆ ZN382_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ osa;Skin_Sun_ ┆ 675.14       ┆ VEZF1_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ Expo…         ┆              ┆ ZN341_…      │
│ chr16 ┆ 1984135   ┆ 1984136   ┆ 2.0      ┆ … ┆ -   ┆ Adipose_Subcu ┆ ENSG00000127 ┆ ETS1_HUMAN;Z │
│       ┆           ┆           ┆          ┆   ┆     ┆ taneous;Adipo ┆ 554.12;ENSG0 ┆ BT7A_HUMAN;E │
│       ┆           ┆           ┆          ┆   ┆     ┆ se_V…         ┆ 000012…      ┆ P300_H…      │
│ chr16 ┆ 15787933  ┆ 15787934  ┆ 2.0      ┆ … ┆ -   ┆ Adipose_Subcu ┆ ENSG00000166 ┆ ZN362_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ taneous;Adipo ┆ 780.10;ENSG0 ┆ ZN384_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ se_V…         ┆ 000017…      ┆ RBM25_…      │
│ chr1  ┆ 28648888  ┆ 28648889  ┆ 2.0      ┆ … ┆ -   ┆ Adipose_Subcu ┆ ENSG00000130 ┆ FOXM1_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ taneous;Adipo ┆ 766.4;ENSG00 ┆ ARNT_HUMAN;I │
│       ┆           ┆           ┆          ┆   ┆     ┆ se_V…         ┆ 000180…      ┆ NT13_H…      │
│ …     ┆ …         ┆ …         ┆ …        ┆ … ┆ …   ┆ …             ┆ …            ┆ …            │
│ chr9  ┆ 128662027 ┆ 128662028 ┆ 3.0      ┆ … ┆ -   ┆ -             ┆ -            ┆ -            │
│ chr11 ┆ 8068451   ┆ 8068452   ┆ 3.0      ┆ … ┆ -   ┆ Colon_Sigmoid ┆ ENSG00000166 ┆ ARI1B_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ ;Colon_Transv ┆ 402.8        ┆ GCR_HUMAN;AN │
│       ┆           ┆           ┆          ┆   ┆     ┆ erse…         ┆              ┆ DR_HUM…      │
│ chr12 ┆ 132472506 ┆ 132472507 ┆ 3.0      ┆ … ┆ -   ┆ Brain_Anterio ┆ ENSG00000112 ┆ SSRP1_HUMAN  │
│       ┆           ┆           ┆          ┆   ┆     ┆ r_cingulate_c ┆ 787.12;ENSG0 ┆              │
│       ┆           ┆           ┆          ┆   ┆     ┆ orte…         ┆ 000017…      ┆              │
│ chr3  ┆ 63564318  ┆ 63564319  ┆ 2.0      ┆ … ┆ -   ┆ -             ┆ -            ┆ ZFX_HUMAN    │
│ chr1  ┆ 228359212 ┆ 228359213 ┆ 2.0      ┆ … ┆ -   ┆ Skin_Not_Sun_ ┆ ENSG00000154 ┆ PRDM9_HUMAN; │
│       ┆           ┆           ┆          ┆   ┆     ┆ Exposed_Supra ┆ 358.20       ┆ HDGF_HUMAN;Z │
│       ┆           ┆           ┆          ┆   ┆     ┆ pubi…         ┆              ┆ SCA4_H…      │
└───────┴───────────┴───────────┴──────────┴───┴─────┴───────────────┴──────────────┴──────────────┘

# Chromatin

In [14]:
# total datasets

!ls Chromatin/as_tables/ | wc -l

211030

In [15]:
# motif-annotated sets of ASchromatin sites

len(pd.read_table('Chromatin/agg_dnase/pvalues_init.tsv')) + len(pd.read_table('Chromatin/agg_atac/pvalues_init.tsv'))

7070

In [16]:
len(pd.read_table('Chromatin/agg_atac/pvalues_agg_greater.tsv'))

219

In [17]:
len(pd.read_table('Chromatin/agg_atac/pvalues_agg_greater.tsv').query('fdr_comb < 0.05'))

20

In [18]:
len(pd.read_table('Chromatin/agg_dnase/pvalues_agg_greater.tsv'))

215

In [19]:
len(pd.read_table('Chromatin/agg_dnase/pvalues_agg_greater.tsv').query('fdr_comb < 0.05'))

48

In [12]:
# unique tfs across dnase and atac
tfs = set()
for file in glob('Chromatin/agg_*/pvalues_agg_greater.tsv'):
    table = pd.read_table(file).query('fdr_comb < 0.05')
    tfs = tfs | set(table['TF'])
len(tfs)

52

In [19]:
controls = pd.read_table('common/tftypes.txt', names=['tf', 'type'])
controls[controls['tf'].isin(tfs)].groupby('type').count()

             tf
type
Codebook TF  33
Control      19